#define GetPlayer(%0,%1) InfoPlayer[%0][%1]
#define GetGreenhouse(%0,%1) GreenhouseData[%0][%1]
#define GetPlayerGreenhouse(%0,%1) PlayerGreenhouseData[%0][%1]

#define public:%0(%1) forward%0(%1);public%0(%1)
#define DialogR:%0() DialogResponse:%0(playerid, response, listitem, inputtext[])

#define COLOR_GREEN "0x259425FF"
#define C_GREEN "{259425}"

#define COLOR_WHITE "0xFFFFFFF F"
#define C_WHITE "{FFFFFF}"
